spring:
  application:
    name: alura-bank
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/alura?serverSelectionTimeoutMS=15000&connectTimeoutMS=15000
  kafka:
    bootstrap-servers: http://0.0.0.0:9092
    topics:
      enviar-pagamento-banco-central: "enviar-pagamento-banco-central"
    properties:
      schema:
        registry:
          url: http://0.0.0.0:8081
      specific:
        avro:
          reader: true
    producer:
      bootstrap-servers: ${spring.kafka.bootstrap-servers}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer